Check if VERSION or RAPIDS_VERSION has changed

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -26,6 +26,11 @@ on:
         default: true
         type: boolean
         required: false
+      enable_check_version_file_changed:
+        description: "Whether to enable the version file changed checker"
+        defualt: true
+        type: boolean
+        required: false
       enable_check_version_against_tag:
         description: "Whether to enable the version tag checker"
         default: true
@@ -42,8 +47,19 @@ defaults:
     shell: bash
 
 jobs:
+  changed-files:
+    secrets: inherit
+    if: ${{ inputs.enable_check_version_file_changed }}
+    uses: ./.github/workflows/changed-files.yaml
+    with:
+      files_yaml: |
+        version_files:
+          - VERSION
+          - RAPIDS_VERSION
+
   other-checks:
     runs-on: ubuntu-latest
+    needs: changed-files
     container:
       image: rapidsai/ci-conda:25.12-latest # zizmor: ignore[unpinned-images]
       env:
@@ -72,6 +88,15 @@ jobs:
         run: rapids-check-pr-job-dependencies "${IGNORED_JOBS}"
         env:
           IGNORED_JOBS: ${{ inputs.ignored_pr_jobs }}
+      - name: Check if VERSION or RAPIDS_VERSION file has changed
+        if: ${{ inputs.enable_check_version_file_changed }}
+        run: |
+          if "$VERSION_FILES_CHANGED"; then
+            echo "ERROR: VERSION or RAPIDS_VERSION file has been changed"
+            exit 1
+          fi
+        env:
+          VERSION_FILES_CHANGED: ${{ fromJSON(needs.changed-files.outputs.changed_file_groups).version_files }}
       - name: Fetch tags
         if: ${{ inputs.enable_check_version_against_tag }}
         uses: actions/checkout@v5
