Check `VERSION` file against tag (#457)

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -26,6 +26,11 @@ on:
         default: true
         type: boolean
         required: false
+      enable_check_version_against_tag:
+        description: "Whether to enable the version tag checker"
+        default: true
+        type: boolean
+        required: false
       ignored_pr_jobs:
         description: "Space separated list of jobs to ignore when checking PR workflow dependencies"
         default: ""
@@ -67,6 +72,22 @@ jobs:
         run: rapids-check-pr-job-dependencies "${IGNORED_JOBS}"
         env:
           IGNORED_JOBS: ${{ inputs.ignored_pr_jobs }}
+      - name: Fetch tags
+        if: ${{ inputs.enable_check_version_against_tag }}
+        uses: actions/checkout@v5
+        with:
+          persist-credentials: false
+          fetch-depth: 0 # https://github.com/actions/checkout/issues/1471
+          fetch-tags: true
+      - name: Check VERSION file against latest tag
+        if: ${{ inputs.enable_check_version_against_tag }}
+        run: |
+          expected_version="$(python -m dunamai from git --format '{base}')"
+          if [ "$expected_version" != "$(cat VERSION)" ]; then
+            echo "ERROR: Expected VERSION file to be \"$expected_version\", got:"
+            cat VERSION
+            exit 1
+          fi
       - name: Telemetry upload attributes
         uses: rapidsai/shared-actions/telemetry-dispatch-stash-job-artifacts@main
         continue-on-error: true
