compute-matrix: Use GHA error formatting (#616)
Authors:
  - Kyle Edwards (https://github.com/KyleFromNVIDIA)

Approvers:
  - James Lamb (https://github.com/jameslamb)

URL: https://github.com/rapidsai/shared-workflows/pull/616

diff --git a/.github/workflows/compute-matrix.yaml b/.github/workflows/compute-matrix.yaml
--- a/.github/workflows/compute-matrix.yaml
+++ b/.github/workflows/compute-matrix.yaml
@@ -201,15 +201,15 @@ jobs:
           MATRIX: ${{ steps.prepare-matrix.outputs.matrix }}
         run: |
           if [[ "$BUILD_TYPE" != "branch" ]] && [[ "$BUILD_TYPE" != "nightly" ]] && [[ "$BUILD_TYPE" != "pull-request" ]]; then
-              echo "Invalid build_type! Must be one of 'branch', 'nightly', or 'pull-request'."
+              echo "::error::Invalid build_type! Must be one of 'branch', 'nightly', or 'pull-request'."
               exit 1
           fi
           if [[ "$MATRIX_TYPE" != "auto" ]] && [[ "$MATRIX_TYPE" != "nightly" ]] && [[ "$MATRIX_TYPE" != "pull-request" ]]; then
-              echo "Invalid matrix_type! Must be one of 'auto', 'nightly', or 'pull-request'."
+              echo "::error::Invalid matrix_type! Must be one of 'auto', 'nightly', or 'pull-request'."
               exit 1
           fi
           if ! jq -n -e '$ENV.MATRIX | fromjson | has($ENV.MATRIX_NAME)'; then
-              echo "Invalid matrix_name! Must be one of '$(jq -n -r "\$ENV.MATRIX | fromjson | keys | join(\"', '\")")'."
+              echo "::error::Invalid matrix_name! Must be one of '$(jq -n -r "\$ENV.MATRIX | fromjson | keys | join(\"', '\")")'."
               exit 1
           fi
       - name: Compute Build Matrix
@@ -245,8 +245,11 @@ jobs:
             MATRIX_FILTER="map(select(.ARCH == \"amd64\")) | group_by(.CUDA_VER|split(\".\")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(\".\")|map(tonumber)), (.CUDA_VER|split(\".\")|map(tonumber))]))"
           fi
 
-          MATRIX="$(
-            jq -n -c "\$ENV.MATRIX | fromjson | .[\$ENV.MATRIX_NAME].[\$ENV.MATRIX_TYPE] | ${MATRIX_FILTER} | if (. | length) > 0 then {include: .} else \"Error: Empty matrix\n\" | halt_error(1) end"
-          )"
+          if ! MATRIX="$(
+            jq -n -c "\$ENV.MATRIX | fromjson | .[\$ENV.MATRIX_NAME].[\$ENV.MATRIX_TYPE] | ${MATRIX_FILTER} | if (. | length) > 0 then {include: .} else \"\" | halt_error(1) end"
+          )"; then
+            echo "::error::Empty matrix"
+            exit 1
+          fi
 
           echo "matrix=${MATRIX}" | tee --append "${GITHUB_OUTPUT}"
