commit pr-builder changes

diff --git a/.github/workflows/pr-builder.yaml b/.github/workflows/pr-builder.yaml
--- a/.github/workflows/pr-builder.yaml
+++ b/.github/workflows/pr-builder.yaml
@@ -15,3 +15,15 @@ jobs:
         env:
           NEEDS: ${{ inputs.needs }}
         run: jq -en 'env.NEEDS | fromjson | all(.result as $result | ["success", "skipped"] | any($result == .))'
+
+      - name: "Check for private token usage"
+        env:
+          NEEDS: ${{ inputs.needs }}
+          ERROR_MSG: "PR validation failed: Private token access is not allowed to be merged onto the development branch"
+        run: |
+          if jq -en 'env.NEEDS | fromjson | to_entries[] | select(.value.inputs.alternative-gh-token-secret-name and .value.inputs.alternative-gh-token-secret-name != "") | length > 0'; then
+            echo "::error::$ERROR_MSG"
+            echo "Jobs using private token:"
+            jq -en 'env.NEEDS | fromjson | to_entries[] | select(.value.inputs.alternative-gh-token-secret-name and .value.inputs.alternative-gh-token-secret-name != "") | "- " + .key'
+            exit 1
+          fi
