Use inherit_errexit in test matrix generation

diff --git a/.github/workflows/wheels-manylinux-test.yml b/.github/workflows/wheels-manylinux-test.yml
--- a/.github/workflows/wheels-manylinux-test.yml
+++ b/.github/workflows/wheels-manylinux-test.yml
@@ -63,13 +63,18 @@ jobs:
           fi
       - name: Compute test matrix
         id: compute-matrix
+        # use bash to support inherit_errexit so that $(jq) subshell failures can propagate
+        shell: bash 
         run: |
+          set -euExo pipefail
+          shopt -s inherit_errexit
+
           export MATRICES='{
             "pull-request": [
               { "arch": "amd64", "python": "3.8", "ctk": "11.8.0", "image": "ubuntu18.04", "test-type": "unit" },
               { "arch": "arm64", "python": "3.8", "ctk": "11.8.0", "image": "ubuntu20.04", "test-type": "smoke" },
               { "arch": "amd64", "python": "3.8", "ctk": "12.0.0", "image": "ubuntu18.04", "test-type": "unit" },
-              { "arch": "arm64", "python": "3.8", "ctk": "12.0.0", "image": "ubuntu20.04", "test-type": "smoke" }
+              { "arch": "arm64", "python": "3.8", "ctk": "12.0.0", "image": "ubuntu20.04", "test-type": "smoke" },
             ],
             "nightly": [
               { "arch": "amd64", "python": "3.8", "ctk": "11.8.0", "image": "ubuntu18.04", "test-type": "unit" },
